#!/usr/bin/env python3
"""agentbundle-catalogue generator for skilldrop. No deps, no network. Run from the
repo root:

    python3 build_catalogue.py            # render the his-schema catalogue into dist/
    python3 build_catalogue.py --check     # render + assert required fields, exit 1 on gap
    python3 build_catalogue.py --out <dir>

Why this exists (RFC-0014). agent-ready-repo's `agentbundle` installs from a catalogue
whose on-disk shape is `packs/<name>/{pack.toml, .claude-plugin/plugin.json, .apm/skills/…}`
plus a root `catalogue.toml` + `.claude-plugin/marketplace.json`, all validated against the
standalone, versioned schemas in that repo's `contracts/` (schema = 1, adapter-contract
v0.14). skilldrop's source of truth is the opposite shape on purpose — flat `skills/<name>`
with *virtual* packs (a skill belongs to several; RFC-0001). Those models can't be one tree,
so we keep flat as canonical and GENERATE the his-schema view here. The generated packs
duplicate a multi-pack skill into each pack folder — which only a build step can do, and the
reason native adoption of his layout was rejected.

The output is meant to be published to a dedicated branch (default `agentbundle-catalogue`);
an agentbundle user then installs with:

    agentbundle install --pack solution-architect git+https://github.com/sananthanarayan/skilldrop@agentbundle-catalogue

Nothing here is committed to main (dist/ is gitignored), and skilldrop-cli / npm are
untouched — this is an export target, not a migration. `agentbundle validate` is the
authoritative check; --check below is a fast stdlib pre-flight on the required fields.
"""
import argparse
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SKILLS = os.path.join(ROOT, "skills")

# Pinned contract knobs — bump deliberately, never track his HEAD (RFC-0014).
# The verifier's spec gate only refuses on a MAJOR mismatch, so 0.x stays compatible;
# 0.17 is the current contract (2026-07, RFC-0076). agentbundle catalogue verify is authoritative.
ADAPTER_CONTRACT = "0.17"        # contracts/ adapter-contract version we target
MIN_AGENTBUNDLE = "0.13.0"       # minimum-agentbundle-version the catalogue declares
DIST_BRANCH = "agentbundle-catalogue"
REPO_SLUG = "sananthanarayan/skilldrop"

# skilldrop keeps a skill's own manifest.json (its schema, not his skill-manifest.schema);
# it is not copied into the generated skill so his validator sees a clean agentskills.io skill.
_SKILL_SKIP = {"manifest.json"}


def _pkg():
    return json.load(open(os.path.join(ROOT, "package.json"), encoding="utf-8"))


def _packs():
    return json.load(open(os.path.join(ROOT, "packs.json"), encoding="utf-8"))["packs"]


def _repo_url(pkg):
    return pkg.get("repository", {}).get("url", "").removeprefix("git+").removesuffix(".git")


# --- tiny TOML emitter (stdlib has no writer) — only the value shapes we emit -------------
def _toml_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_arr(xs):
    return "[" + ", ".join(_toml_str(x) for x in xs) + "]"


def _pack_toml(name, version, description):
    # Required tables per contracts/pack.schema.json + pack-layout.md: [pack] (name,
    # version, description), [pack.adapter-contract] (version), [pack.install] (default-scope).
    # skilldrop skills carry no repo-specific hooks/seeds, so they are user-scope eligible.
    return (
        "[pack]\n"
        f"name = {_toml_str(name)}\n"
        f"version = {_toml_str(version)}\n"
        f"description = {_toml_str(description)}\n"
        "\n"
        "[pack.adapter-contract]\n"
        f"version = {_toml_str(ADAPTER_CONTRACT)}\n"
        "\n"
        "[pack.install]\n"
        'default-scope = "user"\n'
        f"allowed-scopes = {_toml_arr(['user', 'repo'])}\n"
    )


def _catalogue_toml(pkg, packs):
    # Full required shape per contracts/catalogue.schema.json (2020-12, additionalProperties:false —
    # unknown keys are rejected). Root requires schema/catalogue/distribution; [catalogue] requires
    # name/display-name/description/minimum-agentbundle-version + the paths/build/package sub-tables;
    # [distribution.agentbundle] requires preferred-adapter + artifactory. The build/package/artifactory
    # values are inert for us (we don't run agentbundle's own build or its registry) but must be present
    # and schema-valid. preferred-adapter must name a real adapter → "claude-code".
    src = f"git+https://github.com/{REPO_SLUG}@{DIST_BRANCH}"
    include = _toml_arr([f"packs/{n}" for n in packs])
    return (
        "# Generated by build_catalogue.py — do not edit. Source of truth is skilldrop's\n"
        "# flat skills/ + packs.json; this is the agentbundle-schema export (RFC-0014).\n"
        "schema = 1\n"
        "\n"
        "[catalogue]\n"
        'name = "skilldrop"\n'
        'display-name = "skilldrop"\n'
        f"description = {_toml_str(pkg['description'])}\n"
        f"minimum-agentbundle-version = {_toml_str(MIN_AGENTBUNDLE)}\n"
        "\n"
        "[catalogue.paths]\n"
        'packs = "packs"\n'
        'profiles = "profiles"\n'
        'marketplace = ".claude-plugin/marketplace.json"\n'
        'build-output = "dist"\n'
        "\n"
        "[catalogue.build]\n"
        'recipes = ["default"]\n'
        "self-host = false\n"
        'claude-plugin-branch = "main"\n'
        f"marketplace-description = {_toml_str('skilldrop — portable AI-agent skills, as agentbundle packs.')}\n"
        "\n"
        "[catalogue.package]\n"
        f"include = {include}\n"
        "\n"
        "[distribution.agentbundle]\n"
        'preferred-adapter = "claude-code"\n'
        f"default-source = {_toml_str(src)}\n"
        "\n"
        "[distribution.agentbundle.artifactory]\n"
        "enabled = false\n"
    )


def _plugin_json(name, version, description, author, repo):
    return json.dumps({
        "name": name,
        "version": version,
        "description": description,
        "author": author,
        "homepage": repo,
        "repository": repo,
        "license": "MIT",
    }, indent=2, ensure_ascii=False) + "\n"


def _marketplace_json(pkg, packs):
    author = pkg["author"]
    repo = _repo_url(pkg)
    entries = []
    for name, pack in packs.items():
        entries.append({
            "name": name,
            "source": {
                "source": "github",
                "repo": REPO_SLUG,
                "branch": DIST_BRANCH,
                "directory": f"packs/{name}",
            },
            "description": pack["description"],
            "version": pkg["version"],
            "author": author,
        })
    return json.dumps({
        "name": "skilldrop",
        "owner": {"name": author["name"], "url": author["url"]},
        "plugins": entries,
    }, indent=2, ensure_ascii=False) + "\n"


def render(out):
    """Write the whole catalogue under `out`. Returns the out path."""
    pkg, packs = _pkg(), _packs()
    version, repo = pkg["version"], _repo_url(pkg)
    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(os.path.join(out, ".claude-plugin"), exist_ok=True)

    for name, pack in packs.items():
        description = pack["description"]
        pdir = os.path.join(out, "packs", name)
        os.makedirs(os.path.join(pdir, ".claude-plugin"), exist_ok=True)
        _write(os.path.join(pdir, "pack.toml"), _pack_toml(name, version, description))
        _write(os.path.join(pdir, ".claude-plugin", "plugin.json"),
               _plugin_json(name, version, description, pkg["author"], repo))
        for skill in pack["skills"]:
            src = os.path.join(SKILLS, skill)
            dst = os.path.join(pdir, ".apm", "skills", skill)
            shutil.copytree(src, dst, ignore=shutil.ignore_patterns(*_SKILL_SKIP))

    _write(os.path.join(out, "catalogue.toml"), _catalogue_toml(pkg, packs))
    _write(os.path.join(out, ".claude-plugin", "marketplace.json"), _marketplace_json(pkg, packs))
    return out


def _write(path, text):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def check(out):
    """Fast stdlib pre-flight: every generated file exists and carries the fields the
    contracts/ schemas mark required. Not a substitute for `agentbundle validate`."""
    problems = []
    packs = _packs()

    cat = os.path.join(out, "catalogue.toml")
    cat_txt = open(cat, encoding="utf-8").read() if os.path.exists(cat) else ""
    # Every table/key catalogue.schema.json marks required (agentbundle catalogue verify is authoritative).
    for tok in ("schema = 1", "[catalogue]", "minimum-agentbundle-version",
                "[catalogue.paths]", "profiles", "build-output",
                "[catalogue.build]", "recipes", "claude-plugin-branch", "marketplace-description",
                "[catalogue.package]", "include",
                "[distribution.agentbundle]", "preferred-adapter",
                "[distribution.agentbundle.artifactory]", "enabled"):
        if tok not in cat_txt:
            problems.append(f"catalogue.toml missing `{tok}`")

    mkt = os.path.join(out, ".claude-plugin", "marketplace.json")
    if os.path.exists(mkt):
        m = json.load(open(mkt, encoding="utf-8"))
        for key in ("name", "owner", "plugins"):
            if key not in m:
                problems.append(f"marketplace.json missing `{key}`")
        if len(m.get("plugins", [])) != len(packs):
            problems.append("marketplace.json plugin count != pack count")
    else:
        problems.append("marketplace.json not rendered")

    for name in packs:
        pt = os.path.join(out, "packs", name, "pack.toml")
        txt = open(pt, encoding="utf-8").read() if os.path.exists(pt) else ""
        for tok in ("[pack]", "name = ", "version = ", "[pack.install]", "default-scope"):
            if tok not in txt:
                problems.append(f"packs/{name}/pack.toml missing `{tok.strip()}`")
        pj = os.path.join(out, "packs", name, ".claude-plugin", "plugin.json")
        if os.path.exists(pj):
            p = json.load(open(pj, encoding="utf-8"))
            for key in ("name", "version", "description"):
                if key not in p:
                    problems.append(f"packs/{name}/plugin.json missing `{key}`")
        else:
            problems.append(f"packs/{name}/plugin.json not rendered")
        # every skill in the pack projected as an agentskills.io SKILL.md
        for skill in packs[name]["skills"]:
            if not os.path.exists(os.path.join(out, "packs", name, ".apm", "skills", skill, "SKILL.md")):
                problems.append(f"packs/{name}/.apm/skills/{skill}/SKILL.md missing")
    return problems


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=os.path.join(ROOT, "dist"), help="output dir (default: dist/)")
    ap.add_argument("--check", action="store_true", help="render then assert required fields; exit 1 on gap")
    args = ap.parse_args()
    out = render(args.out)
    n_packs = len(_packs())
    n_skills = sum(len(p["skills"]) for p in _packs().values())
    if args.check:
        problems = check(out)
        if problems:
            print(f"-- {len(problems)} problem(s) --")
            for p in problems:
                print("  ", p)
            sys.exit(1)
        print(f"OK: {n_packs} packs / {n_skills} skill-projections satisfy the required fields")
        return
    print(f"wrote {n_packs} packs ({n_skills} skill-projections) to {os.path.relpath(out, ROOT)}/")


if __name__ == "__main__":
    main()
