#!/usr/bin/env python3
"""build_pack_guides.py — a how-to and a reference page for every pack, generated.

Each pack gets two guides in the docs portal, written from the same sources the site and
CLI read (pack.json, each skill's manifest.json and SKILL.md, loop.json), so they can't
drift from the catalogue:

  guides/how-to/packs/use-the-<pack>-pack.md   install, first task, a typical session, its loops
  guides/reference/packs/pack-<pack>.md        every skill: what it makes, what it needs,
                                               its quality bar, what it hands off to, and
                                               what it isn't for

Usage:
  python3 build_pack_guides.py            # write
  python3 build_pack_guides.py --check    # exit 1 if anything on disk is stale

Stdlib only, and Python 3.9-safe: validate.py imports stale() on every pull request.
"""
import json
import os
import re
import sys

import catalog

ROOT = os.path.dirname(os.path.abspath(__file__))
HOWTO_DIR = os.path.join(ROOT, "guides", "how-to", "packs")
REF_DIR = os.path.join(ROOT, "guides", "reference", "packs")
SITE = "https://sananthanarayan.github.io/skilldrop/"
UP = "../../../"  # from guides/<kind>/packs/ back to the repo root
GENERATED = "<!-- Generated by build_pack_guides.py from pack.json and the skills' own files. Edit those, not this. -->"


def section(md, heading):
    """Bullets under `## heading` in a SKILL.md, wrapped lines joined."""
    m = re.search(r"^## " + re.escape(heading) + r"\s*\n(.*?)(?=^## |\Z)", md, re.M | re.S)
    if not m:
        return []
    out = []
    for line in m.group(1).splitlines():
        if line.startswith("- "):
            out.append(line[2:].strip())
        elif out and line.startswith("  ") and line.strip():
            out[-1] += " " + line.strip()
    return out


def rebase(text, skill_rel):
    """Links in text copied from a SKILL.md are relative to the skill folder; make them
    relative to the generated guide instead."""
    def fix(m):
        target = m.group(2)
        if re.match(r"[a-z]+:|#|/", target):
            return m.group(0)
        path, _, frag = target.partition("#")
        new = UP + os.path.normpath(os.path.join(skill_rel, path)).replace(os.sep, "/")
        return "[{0}]({1}{2})".format(m.group(1), new, "#" + frag if frag else "")
    return re.sub(r"\[([^\]]*)\]\(([^)\s]+)\)", fix, text)


def split_desc(desc):
    """'What it makes. Use when …' -> ('What it makes.', 'Use when …')."""
    i = desc.find(" Use when")
    return (desc, "") if i < 0 else (desc[:i].strip(), desc[i + 1:].strip())


def skill_info(name):
    d = catalog.skill_dir(name)
    m = json.load(open(os.path.join(d, "manifest.json"), encoding="utf-8"))
    md = open(os.path.join(d, "SKILL.md"), encoding="utf-8").read()
    return {"name": name, "m": m, "md": md, "rel": catalog.rel(d)}


def install_lines(name):
    return [
        "```bash",
        "npx skilldrop-cli install --pack {0}                 # Claude Code, your user folder".format(name),
        "npx skilldrop-cli install --pack {0} --project       # Claude Code, this repo".format(name),
        "npx skilldrop-cli install --pack {0} --ide cursor    # or kiro, codex, antigravity, copilot".format(name),
        "npx skilldrop-cli install --pack {0} --local         # this repo, hidden from git".format(name),
        "```",
        "",
        "In Claude Code you can also add the marketplace once (`/plugin marketplace add sananthanarayan/skilldrop`) "
        "and run `/plugin install {0}@skilldrop`.".format(name),
    ]


def howto(name, pack, packs):
    title = pack.get("display_name", name)
    fv = pack.get("first-value") or {}
    j = pack.get("journey") or {}
    reqs = [r for r in pack.get("requires", []) if r in packs]
    L = ["---", "title: Use the {0} pack".format(title),
         "summary: Install the {0} pack, run its first task, and follow a typical session step by step.".format(title),
         "kind: how-to", "---", "", "# Use the {0} pack".format(title), "", GENERATED, "",
         pack["description"], ""]
    if j.get("when"):
        L += ["**Reach for it when:** " + j["when"], ""]
    L += ["## 1. Install it", ""] + install_lines(name) + [""]
    if reqs:
        L += ["It brings {0} with it, so the shared skills are there too.".format(
            ", ".join("`{0}`".format(r) for r in reqs)), ""]
    if fv:
        L += ["## 2. Run the first task: {0}".format(fv["starter-task"][0].lower() + fv["starter-task"][1:]), ""]
        if fv.get("prerequisites"):
            L += ["Before you start:", ""] + ["- " + p for p in fv["prerequisites"]] + [""]
        L += ["Paste this into your agent:", "", "```text", fv["starter-prompt"], "```", "",
              "**How to tell it worked:** " + fv["verification"], "",
              "**If nothing happens:** " + fv["recovery"], ""]
    if j.get("steps"):
        L += ["## 3. A typical session", ""]
        if j.get("you_bring"):
            L += ["Bring:", ""] + ["- " + b for b in j["you_bring"]] + [""]
        if j.get("time"):
            L += ["A session takes about {0}.".format(j["time"]), ""]
        for i, st in enumerate(j["steps"], 1):
            L += ["{0}. **`{1}`**: {2}".format(i, st["skill"], st["you_do"]),
                  "   You get: {0}".format(st["you_get"])]
            if st.get("decide"):
                L.append("   **You decide:** {0}".format(st["decide"]))
        L += ["", "You end with: " + j["you_end_with"], ""]
    loops = pack.get("loops", [])
    if loops:
        L += ["## 4. Run it as a loop", "",
              "A loop runs the skills in order and stops at each gate for a verdict. Install and start one:", "",
              "```bash", "npx skilldrop-cli install --loop --pack {0}".format(name), "```", ""]
        for lp in loops:
            spec = json.load(open(os.path.join(catalog.loop_dir(lp), "loop.json"), encoding="utf-8"))
            stages = " → ".join(st["id"] + (" [{0}]".format(st["gate"]["id"]) if st.get("gate") else "")
                                for st in spec.get("stages", []))
            L += ["- **{0}**: {1} Say \"run the {0} loop on this\". Stages: {2}.".format(
                lp, split_desc(spec.get("description", ""))[0], stages)]
        L.append("")
    L += ["## Next", "",
          "- [Every skill in the {0} pack](../../reference/packs/pack-{1}.md): what each one makes, needs and hands off to".format(title, name),
          "- [The pack's page]({0}packs/{1}/), with one-click copy for every command".format(SITE, name),
          "- [Upgrade installed skills](../upgrade-skills.md) when a new version ships", ""]
    return "\n".join(L)


def reference(name, pack, packs):
    title = pack.get("display_name", name)
    reqs = [r for r in pack.get("requires", []) if r in packs]
    L = ["---", "title: {0} pack reference".format(title),
         "summary: Every skill in the {0} pack — what it makes, when to use it, what it needs, its quality bar, and what it hands off to.".format(title),
         "kind: reference", "---", "", "# {0} pack reference".format(title), "", GENERATED, "",
         pack["description"], "",
         "| | |", "|---|---|",
         "| Install | `npx skilldrop-cli install --pack {0}` |".format(name),
         "| Skills | {0}{1} |".format(len(pack["skills"]),
                                     " plus {0} from {1}".format(sum(len(packs[r]["skills"]) for r in reqs), ", ".join(reqs)) if reqs else ""),
         "| Loops | {0} |".format(", ".join(pack.get("loops", [])) or "none"),
         "| How-to | [Use the {0} pack](../../how-to/packs/use-the-{1}-pack.md) |".format(title, name), ""]
    L += ["## Skills", ""]
    for s in sorted(pack["skills"]):
        info = skill_info(s)
        m, md = info["m"], info["md"]
        makes, when = split_desc(m["description"])
        tier = (m.get("model") or {}).get("tier", "?")
        L += ["### `{0}`".format(s), "", makes, "",
              "Tier **{0}** · v{1} · [SKILL.md]({2}{3}/SKILL.md) · [skill page]({4}skills/{5}/)".format(
                  tier, m.get("version", "?"), UP, info["rel"], SITE, s), ""]
        if when:
            L += ["**Use it when** " + re.sub(r"^Use when ", "", when), ""]
        needs = []
        pip = (m.get("deps") or {}).get("pip") or []
        env_req = (m.get("env") or {}).get("required") or []
        if os.path.isdir(os.path.join(catalog.skill_dir(s), "scripts")):
            needs.append("Python 3 for its scripts" + (" plus " + ", ".join(pip) if pip else " (standard library only)"))
        if env_req:
            needs.append("environment: " + ", ".join("`{0}`".format(e) for e in env_req))
        if needs:
            L += ["**Needs:** " + "; ".join(needs) + ".", ""]
        bar = section(md, "Quality bar")
        if bar:
            L += ["**A good result:**", ""] + ["- " + rebase(b, info["rel"]) for b in bar] + [""]
        hand = m.get("handoff") or []
        if hand:
            L += ["**Hands off to:** " + "; ".join("`{0}` when {1}".format(h["to"], h["when"]) for h in hand) + ".", ""]
        notfor = section(md, "When NOT to use this skill")
        if notfor:
            L += ["**Not for:**", ""] + ["- " + rebase(n.replace("❌", "").strip(), info["rel"]) for n in notfor] + [""]
    loops = pack.get("loops", [])
    if loops:
        L += ["## Loops", ""]
        for lp in loops:
            spec = json.load(open(os.path.join(catalog.loop_dir(lp), "loop.json"), encoding="utf-8"))
            L += ["### `{0}`".format(lp), "", split_desc(spec.get("description", ""))[0], "",
                  "| Stage | Skills | Gate |", "|---|---|---|"]
            for st in spec.get("stages", []):
                g = st.get("gate")
                L.append("| {0} | {1} | {2} |".format(
                    st["id"], ", ".join("`{0}`".format(x) for x in st.get("skills", [])),
                    "{0} {1}: {2}".format(g["id"], g["kind"], " / ".join(g.get("verdicts", []))) if g else "—"))
            L += ["", "Cap: {0} returns before `BLOCKED`. [LOOP.md]({1}{2}/LOOP.md)".format(
                spec.get("cap", 3), UP, catalog.rel(catalog.loop_dir(lp))), ""]
    for r in reqs:
        L += ["## Included from {0}".format(r), "",
              "Installed with this pack. Details: [{0} pack reference](pack-{1}.md).".format(
                  packs[r].get("display_name", r), r), ""]
        L += ["- `{0}`: {1}".format(s, split_desc(skill_info(s)["m"]["description"])[0]) for s in sorted(packs[r]["skills"])]
        L.append("")
    return "\n".join(L)


INDEX = os.path.join(ROOT, "guides", "README.md")
MARK_A, MARK_B = "<!-- pack-guides:start -->", "<!-- pack-guides:end -->"


def index_block(packs):
    rows = ["| Pack | How-to | Reference |", "|---|---|---|"]
    for name, pack in packs.items():
        t = pack.get("display_name", name)
        rows.append("| {0} | [Use the {0} pack](how-to/packs/use-the-{1}-pack.md) | [{0} pack reference](reference/packs/pack-{1}.md) |".format(t, name))
    return "\n".join(rows)


def render():
    packs = catalog.packs()
    out = {}
    idx = open(INDEX, encoding="utf-8").read()
    a, b = idx.find(MARK_A), idx.find(MARK_B)
    if a >= 0 and b > a:
        out[INDEX] = idx[:a + len(MARK_A)] + "\n" + index_block(packs) + "\n" + idx[b:]
    for name, pack in packs.items():
        out[os.path.join(HOWTO_DIR, "use-the-{0}-pack.md".format(name))] = howto(name, pack, packs)
        out[os.path.join(REF_DIR, "pack-{0}.md".format(name))] = reference(name, pack, packs)
    return out


def stale():
    """Relative paths whose content differs from what render() would write, plus generated
    files for packs that no longer exist."""
    want = render()
    bad = []
    for p, body in want.items():
        cur = open(p, encoding="utf-8").read() if os.path.exists(p) else None
        if cur != body:
            bad.append(os.path.relpath(p, ROOT))
    if INDEX not in want:
        bad.append("guides/README.md (no pack-guides markers)")
    for d in (HOWTO_DIR, REF_DIR):
        if os.path.isdir(d):
            for f in os.listdir(d):
                p = os.path.join(d, f)
                if f.endswith(".md") and p not in want:
                    bad.append(os.path.relpath(p, ROOT))
    return bad


def main():
    if "--check" in sys.argv:
        bad = stale()
        for b in bad:
            print("build_pack_guides: {0} is stale — run `python3 build_pack_guides.py`".format(b), file=sys.stderr)
        if not bad:
            print("build_pack_guides: every pack guide is current")
        return 1 if bad else 0
    want = render()
    for d in (HOWTO_DIR, REF_DIR):
        os.makedirs(d, exist_ok=True)
        for f in os.listdir(d):
            if f.endswith(".md") and os.path.join(d, f) not in want:
                os.remove(os.path.join(d, f))
    for p, body in want.items():
        with open(p, "w", encoding="utf-8") as f:
            f.write(body)
    print("build_pack_guides: wrote {0} guides for {1} packs, and the index in guides/README.md".format(len(want) - 1, (len(want) - 1) // 2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
